# netlify.toml

[[redirects]]
  from = "/login"
  to = "/board/login.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/board/admin.html"
  status = 200

[[redirects]]
  from = "/student"
  to = "/board/student.html"
  status = 200

[[redirects]]
  from = "/board/b/*"
  to = "/board/index.html"
  status = 200
